#! /usr/bin/env python3
# -*- coding: utf-8 -*-

import io
import sys
from parse import get_chains
from generate import generate_with_checks

fi = io.TextIOWrapper(sys.stdin.buffer, encoding='utf-8')

corpus = []

for line in fi:
	corpus.append(line)

c1, c2 = get_chains(corpus)

try:
	maxlen = int(sys.argv[1])
except (ValueError, IndexError):
	maxlen = 140

g = generate_with_checks(maxlen, c1, c2, corpus, [])

print(g)

